name: Build macOS App


on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --windowed --distpath dist main.py

      - name: Make the executable executable
        run: |
          chmod +x dist/main
          ls -l dist/main

      - name: Remove quarantine attribute
        run: |
          xattr -d com.apple.quarantine dist/main || true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-executable
          path: dist/main
